// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Poe.Button = (function(_super) {
    __extends(Button, _super);

    function Button(toolbar, text, tooltip, tooltipPos) {
      if (text == null) {
        text = "";
      }
      if (tooltip == null) {
        tooltip = "";
      }
      if (tooltipPos == null) {
        tooltipPos = "right";
      }
      this.button = $('<button type="button" class="btn btn-default"></button>');
      this.text = $('<span class="text"></span>');
      this.setText(text);
      toolbar.element.append(this.button);
      this.button.append(this.text);
      if (tooltip !== "") {
        this.setTooltip(tooltip, tooltipPos);
      }
    }

    Button.prototype.setText = function(text) {
      return this.text.html(text);
    };

    Button.prototype.setTooltip = function(text, position) {
      this.button.addClass('poe-tooltip');
      this.button.attr('title', text);
      return this.button.attr('data-placement', position);
    };

    Button.prototype.setIcon = function(icon) {
      return this.button.prepend(icon.element());
    };

    Button.prototype.on = function(event, callback) {
      if (event === 'click') {
        return this.button.click(callback);
      }
    };

    Button.prototype.element = function() {
      return this.button;
    };

    Button.prototype.active = function(onoff) {
      if (onoff) {
        return this.button.addClass('active');
      } else {
        return this.button.removeClass('active');
      }
    };

    return Button;

  })(Poe.ToolBarItem);

}).call(this);

//# sourceMappingURL=Button.js.map
