// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Poe.Glyphicon = (function(_super) {
    __extends(Glyphicon, _super);

    function Glyphicon(icon, parent) {
      if (icon == null) {
        icon = 'tree-conifer';
      }
      this.span = $('<span class="glyphicon"></span>');
      this.setIcon(icon);
      if (parent) {
        this.parent.element().prepend(this.span);
      }
    }

    Glyphicon.prototype.setIcon = function(icon) {
      this.span.attr('class', 'glyphicon');
      icon = 'glyphicon-' + icon;
      return this.span.addClass(icon);
    };

    Glyphicon.prototype.element = function() {
      return this.span;
    };

    return Glyphicon;

  })(Poe.ToolBarItem);

}).call(this);

//# sourceMappingURL=Glyphicon.js.map
