// Generated by CoffeeScript 1.8.0

/*
Poe.ToolBar handles items on the Writer's toolbar. It uses the {Poe.TextCursor}
provided by Poe.Writer.document to apply styles to the text.

@todo Make Poe.ToolBar create all of the elements itself.
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Poe.ToolBar = (function() {

    /*
    Creates a new Poe.ToolBar instance.
     */
    function ToolBar(writer) {
      this.writer = writer;
      this.handleList = __bind(this.handleList, this);
      this.handleFontColor = __bind(this.handleFontColor, this);
      this.handleTextAlignment = __bind(this.handleTextAlignment, this);
      this.paragraphStyleChanged = __bind(this.paragraphStyleChanged, this);
      this.handleFontSizeClick = __bind(this.handleFontSizeClick, this);
      this.handleFontClick = __bind(this.handleFontClick, this);
      this.handleShortcut = __bind(this.handleShortcut, this);
      this.clickToggle = __bind(this.clickToggle, this);
      this.textStyleChanged = __bind(this.textStyleChanged, this);
      if (!this.writer) {
        throw new Error('new Poe.Toolbar takes exactly one argument of type Poe.Writer');
      }
      this.textCursor = this.writer.document.textCursor;
      this.textStyle = this.textCursor.textStyle;
      this.textStyle.changed(this.textStyleChanged);
      this.paragraphStyle = this.textCursor.paragraphStyle;
      this.paragraphStyle.changed(this.paragraphStyleChanged);
      this.element = $('.toolbar');
      this.elements = {
        bold: $('.bold'),
        italic: $('.italic'),
        underline: $('.underline'),
        font: $('#font-select .text'),
        fontSize: $('#font-size-select .text'),
        color: $('#color-pick'),
        list: {
          bullet: $('#list-bullet'),
          number: $('#list-number')
        },
        align: {
          left: $('#align-left'),
          center: $('#align-center'),
          right: $('#align-right'),
          justify: $('#align-justify')
        }
      };
      this.textStyleChanged(this.textStyle);
      this.paragraphStyleChanged(this.paragraphStyle);
      this.elements.bold.click(this.clickToggle);
      this.elements.italic.click(this.clickToggle);
      this.elements.underline.click(this.clickToggle);
      $('body').keydown(this.handleShortcut);
      $('#font-list li').click(this.handleFontClick);
      $('#font-size-list li').click(this.handleFontSizeClick);
      $('#alignment button').click(this.handleTextAlignment);
      $('#color-list .color-list-item').click(this.handleFontColor);
      $('#lists button').click(this.handleList);
    }


    /*
    A callback given to Poe.TextCursor.textStyle.
    @see Poe.TextStyle#changed
    @param style [Poe.TextStyle] the style to update the toolbar with
    @private
     */

    ToolBar.prototype.textStyleChanged = function(style) {
      var activate;
      activate = function(toolItem, isTrue) {
        if (isTrue) {
          return toolItem.addClass('active');
        } else {
          return toolItem.removeClass('active');
        }
      };
      this.textStyle = style;
      activate(this.elements.bold, style.bold);
      activate(this.elements.italic, style.italic);
      activate(this.elements.underline, style.underline);
      this.elements.font.html(style.font);
      this.elements.fontSize.html(style.fontSize);
      return this.elements.color.css('background-color', style.color);
    };


    /*
    A event handler for when a button is clicked on the toolbar
    @param event [MouseClickEvent] the event that happend
    @private
     */

    ToolBar.prototype.clickToggle = function(event) {
      if (event.target === this.elements.bold[0]) {
        this.textStyle.bold = !this.textStyle.bold;
      } else if (event.target === this.elements.italic[0]) {
        this.textStyle.italic = !this.textStyle.italic;
      } else if (event.target === this.elements.underline[0]) {
        this.textStyle.underline = !this.textStyle.underline;
      }
      this.textStyle.applyChar();
      return this.textStyleChanged(this.textStyle);
    };


    /*
    A even handler for toolbar shortcuts. Returns immediately if
    the control key is not pressed.
    @param event [MouseDownEvent] the event
    @private
     */

    ToolBar.prototype.handleShortcut = function(event) {
      var toggle;
      if (!event.ctrlKey) {
        return;
      }
      toggle = (function(_this) {
        return function(button) {
          button.toggleClass('active');
          if (button === _this.elements.bold) {
            _this.textStyle.bold = !_this.textStyle.bold;
          } else if (button === _this.elements.italic) {
            _this.textStyle.italic = !_this.textStyle.italic;
          } else if (button === _this.elements.underline) {
            _this.textStyle.underline = !_this.textStyle.underline;
          }
          _this.textStyle.applyChar();
          return _this.textStyleChanged(_this.textStyle);
        };
      })(this);
      switch (event.keyCode) {
        case Poe.key.B:
          event.preventDefault();
          return toggle(this.elements.bold);
        case Poe.key.I:
          event.preventDefault();
          return toggle(this.elements.italic);
        case Poe.key.U:
          event.preventDefault();
          return toggle(this.elements.underline);
        default:
          return event.preventDefault();
      }
    };


    /*
    Event handler for when a new font is clicked. Updates
    the current style and applies the style
    @param event [MouseClickEvent] the event that happened.
    @private
     */

    ToolBar.prototype.handleFontClick = function(event) {
      var name;
      name = $(event.target).html();
      this.elements.font.html(name);
      this.textStyle.font = name;
      return this.textStyle.applyChar();
    };


    /*
    Event handler for when a font size is clicked.
    @param event [MouseClickEvent] the event that triggered the callback
    @private
     */

    ToolBar.prototype.handleFontSizeClick = function(event) {
      var name;
      name = $(event.target).html();
      this.elements.fontSize.html(parseInt(name.replace('px', '')));
      this.textStyle.fontSize = parseInt(name.replace('px', ''));
      return this.textStyle.applyChar();
    };


    /*
    Called when the line style changes of the {Poe.TextCursor}
    @param style [Poe.ParagraphStyle] the style that has changed
    @private
     */

    ToolBar.prototype.paragraphStyleChanged = function(style) {
      var element;
      this.elements.align.left.removeClass('active');
      this.elements.align.center.removeClass('active');
      this.elements.align.right.removeClass('active');
      this.elements.align.justify.removeClass('active');
      switch (style.align) {
        case Poe.ParagraphStyle.Align.Left:
          element = this.elements.align.left;
          break;
        case Poe.ParagraphStyle.Align.Center:
          element = this.elements.align.center;
          break;
        case Poe.ParagraphStyle.Align.Right:
          element = this.elements.align.right;
          break;
        case Poe.ParagraphStyle.Align.Justify:
          element = this.elements.align.justify;
      }
      return element.addClass('active');
    };


    /*
    Event handler for text align buttons in the toolbar.
    @param event [MouseClickEvent] the event that triggered this callback
    @private
     */

    ToolBar.prototype.handleTextAlignment = function(event) {
      var target;
      target = event.target;
      if (target === this.elements.align.left[0]) {
        this.paragraphStyle.align = Poe.ParagraphStyle.Align.Left;
      } else if (target === this.elements.align.center[0]) {
        this.paragraphStyle.align = Poe.ParagraphStyle.Align.Center;
      } else if (target === this.elements.align.right[0]) {
        this.paragraphStyle.align = Poe.ParagraphStyle.Align.Right;
      } else if (target === this.elements.align.justify[0]) {
        this.paragraphStyle.align = Poe.ParagraphStyle.Align.Justify;
      }
      return this.paragraphStyle.apply();
    };


    /*
    Event handler for text color.
    @param
     */

    ToolBar.prototype.handleFontColor = function(event) {
      var color, target;
      target = $(event.target);
      color = target.css('background-color');
      this.elements.color.css('background-color', color);
      this.textStyle.color = color;
      return this.textStyle.applyChar();
    };


    /*
    Event handler for list buttons. Creates a new list when
    the button is clicked.
    @param event [MouseClickEvent] the event that triggered the function
     */

    ToolBar.prototype.handleList = function(event) {
      var list, paragraph, target;
      target = event.target;
      list = new Poe.List();
      if (target === this.elements.list.bullet[0]) {
        list.setListType(Poe.List.ListType.Bullets);
      } else if (target === this.elements.list.number[0]) {
        list.setListType(Poe.List.ListType.Numbers);
      }
      paragraph = this.textCursor.currentParagraph();
      list.insertAfter(this.textCursor.currentParagraph());
      this.textCursor.moveInside(list.child(0).child(0));
      this.textStyle.applyChar();
      if (paragraph.isEmpty()) {
        return paragraph.remove();
      }
    };

    return ToolBar;

  })();

}).call(this);

//# sourceMappingURL=Toolbar.js.map
