// Generated by CoffeeScript 1.8.0

/*
Content.xml
 */

(function() {
  OpenDocument.Content = (function() {
    function Content() {
      this.file = document.implementation.createDocument("urn:oasis:names:tc:opendocument:xmlns:text:1.0", "office:document-content");
      this.autoStyles = document.createElement('office:automatice-styles');
      this.fontFaceDecls = document.createElement('office:font-face-decls');
      this.body = document.createElement('office:body');
      this.file.documentElement.appendChild(this.body);
      this.file.documentElement.appendChild(this.autoStyles);
      this.file.documentElement.appendChild(this.fontFaceDecls);
      this.text = document.createElement('office:text');
      this.body.appendChild(this.text);
      console.log(this.file);
    }

    return Content;

  })();

}).call(this);

//# sourceMappingURL=Content.js.map
